version: '3.9'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: myapp-server
    container_name: server
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - mongo0
    env_file: ./server/.env
    environment:
      - NODE_ENV=development
    networks:
      - app-network
    entrypoint: ["npm", "start"]

  mongo0:
    hostname: mongo0
    container_name: mongo0
    image: mongo:latest
    volumes:
      - volume-0:/data/db
      - /etc/localtime:/etc/localtime
    networks:
      - app-network
    restart: "no"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: myapp-client
    container_name: client
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"
    env_file: ./server/.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  volume-0:
  node_modules:
  web-root:
    driver: local