version: '3.9'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: myapp-server
    container_name: myapp-node-server
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - mongo0
#      - mongo1
#      - mongo2
    env_file: ./server/.env
    environment:
      - NODE_ENV=development
    networks:
      - app-network
    entrypoint: ["npm", "start"]

  mongo0:
    hostname: mongo0
    container_name: mongo0
    image: mongo:latest
    volumes:
      - volume-0:/data/db
      - /etc/localtime:/etc/localtime
#      - ./mongo0_custom_entrypoint.sh:/usr/bin/mongo0_custom_entrypoint.sh
#    ports:
#      - 27018:27018
    networks:
      - app-network
    restart: "no"
#    entrypoint: /usr/bin/mongo0_custom_entrypoint.sh

#  mongo1:
#    hostname: mongo1
#    container_name: mongo1
#    image: mongo:latest
#    volumes:
#      - volume-1:/data/db
#      - /etc/localtime:/etc/localtime
#    ports:
#      - 27019:27019
#    networks:
#      - app-network
#    restart: "no"
#    entrypoint: [ "/usr/bin/mongod", "--bind_ip", "mongo1", "--replSet", "dockerrs", "--port", "27019" ]
#
#  mongo2:
#    hostname: mongo2
#    container_name: mongo2
#    image: mongo:latest
#    volumes:
#      - volume-2:/data/db
#      - /etc/localtime:/etc/localtime
#    ports:
#      - 27020:27020
#    networks:
#      - app-network
#    restart: "no"
#    entrypoint: [ "/usr/bin/mongod", "--bind_ip", "mongo2", "--replSet", "dockerrs", "--port", "27020" ]

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: myapp-client
    container_name: myapp-react-client
#    command: npm run start
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"
    env_file: ./server/.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  volume-0:
  volume-1:
  volume-2:
  node_modules:
  web-root:
    driver: local